vich_uploader:
    db_driver: orm

    mappings:
        artworks:
            uri_prefix: /pics/artworks
            upload_destination: '../public/pics/artworks'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
